### PR TITLE
update icepack; switch to "no abort" when inconsistent ITD condition is found

### PR DESCRIPTION
**Pull request by DeniseWorthen**
- Updates Icepack to Consortium/Icepack master
- Implements the Consortium fix for the ``hicen_init(n+1) <= hicen_init(n)`` condition present in current CICE6 IC conditions. This condition was first reported by EMC when the coupled model failed the debug test. Since then, we have carried a fix for this condition which relied on setting the value ``denom = max(puny,hicen_init(n+1) - hicen_init(n))`` when interpolating between adjacent category growth rates. The relevant code is in ``icepack_therm_itd``.
- The Consortium eventually implemented a fix which included causing the model to abort when the condition is encountered. This PR uses that fix but switches the abort flag to false. Setting the abort flag to false will create a warning in the log file when the condition is encountered rather than aborting the model. 
- Testing indicates that for the tested configurations and ICs, this condition, if found, occurs only at initialization.
- Testing also indicates that this condition is not encountered in the current RT benchmark configurations or any DATM configurations.

### CODE REVIEW

**Review by junwang-noaa — APPROVED** [review]
Thanks for updating icepack. Is there a plan at Consortium repo to fix the hicen_init issue in the ICs so that we don't need to carry the fix?

**Comment by DeniseWorthen** [comment]
I can check more directly w/ Tony, but I believe they feel it is a rare error which there is no fix for at this point so trapping it was the best solution. My testing tends to confirm that---I believe it is only our CFSR-derived ICs that gave the error (the 2016-10-03 case) and only at the first timestep. I don't really believe that other failures we see in CICE in the prototypes are related. That is one reason I wanted to be able to implement their fix vs maintaining our original fix. This way it will report in the log if this is happening. 

I think our best option at this point is to find a way to have the abort flag set optionally so it isn't hardwired. If we could set that by namelist for example then we could point directly at the top of Icepack.

**Comment by junwang-noaa** [comment]
Yes, using namelist variable to control the abort flag would be nice.

**Review by JessicaMeixner-NOAA — APPROVED** [review]

**Comment by JessicaMeixner-NOAA** [comment]
If it's just the CFSR (and not CPC) ice ICs, could we switch to just using the CPC ice ICs and then revert to the "bail out"?

**Comment by JessicaMeixner-NOAA** [comment]
If it's just the CFSR (and not CPC) ice ICs, could we switch to just using the CPC ice ICs and then revert to the "bail out"?

**Pull request merged**
